import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "./components/Session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <html lang="en" className="bg-gradient-to-br from-[#FFC061] to-[#FF004D] bg-no-repeat bg-auto min-h-screen">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
